- shell.default.nix
- shell.example.nix
- shell.nix
Co-authored-by: Alexander Groleau <source@proof.construction>
> build: default and example shell

- .github/workflows/ci.yaml
- src/repl/driver.rs
> build: add fmt check job

- .github/workflows/ci.yaml
Co-authored-by: adrianEffe <adrian.iosdev@gmail.com>
> build: ci overhaul

- Cargo.lock
- Cargo.toml
> fix: pty-process from fork

- .github/workflows/release.yaml
> build: continuous delivery

- Cargo.toml
- src/main.rs
> feat: cargo metadata

- crates/eelco/tests/simple.rs
- crates/util/src/lib.rs
> test: with_eelco utility

- crates/eelco/src/examples.rs
- crates/eelco/src/main.rs
- crates/eelco/src/repl/example.rs
> refactor: move obtain to examples module

- src/app/state.rs
> refactor: extract State::fmt_pass

- tests/misc.rs
Co-authored-by: furioncycle <ttecho2021@gmail.com>
> test: test all_examples_tested

- src/app.rs
- src/app/state.rs
- src/eprintln_driver.rs
- src/main.rs
- **refactor: add eprintln driver**
- **refactor: State::event**
- **fix: race between printing to stderr and terminating**
> stderr exit race

- tests/misc.rs
- tests/repl.rs
- **test: correct linebreaks in repl tests**
- **test: add missing assertion to some test**
- **test: repl assignment**
> test fixes

- src/app/state/repl_state.rs
- src/repl/example.rs
- **refactor: ReplEntry::new**
> repl entry new

- src/app/state.rs
- src/app/state/repl_state.rs
- src/repl/driver.rs
- src/repl/example.rs
- tests/misc.rs
- tests/repl.rs
- **feat: support assignment in repl examples**
> subsequent repl test

- src/main.rs
> command version about

- .github/workflows/check.yaml
- **build: release job on branch main**
> fix release branch name

- flake.nix
- **fix: skip tests in nix pkg**
> flake skip check

- .github/workflows/check.yaml
- **build: bump actions/checkout@v4**
> actions v4

- default.nix
- flake.lock
- flake.nix
- **feat: non-flake export using flake-compat**
> flake compat

- src/examples.rs
- src/expression.rs
- src/repl/example.rs
- tests/repl.rs
- **refactor: dedupe a line in example parsing**
- **refactor: dedupe example id creation**
- **fix: eprint example id when failing to parse it**
> repl example parse fail file line

- README.md
- **docs: explain homage to Eelco Dolstra**
> eelco homage

- src/app/state.rs
- src/app/state/repl_state.rs
Co-authored-by: ruben beck <ruben.beck@pm.me>
> refactor: variant ReplSessionExpecting::ResultAndNextPrompt

- src/app/state/repl_state.rs
- src/repl/driver.rs
- src/repl/example.rs
- tests/repl.rs
Co-authored-by: ruben beck <ruben.beck@pm.me>
> feat: multiline results

- src/app/state.rs
- src/repl/driver.rs
> refactor: variant ReplEvent::Error

- src/app/state.rs
- tests/repl.rs
> feat: rewrite result mismatch error

- flake.nix
- **chore: rm relic comment**
- **chore: explain doCheck = false better**
> explain do check false better

- flake.nix
> build: run unit tests in derivation

- src/app/state.rs
- src/app/state/repl_state.rs
Co-authored-by: kurogeek <panupong.jtp@gmail.com>
Co-authored-by: furioncycle <ttecho2021@gmail.com>
> feat: no bail on first unexpected repl char

- flake.nix
- src/app/state.rs
- src/app/state/repl_state.rs
Co-authored-by: kurogeek <panupong.jtp@gmail.com>
Co-authored-by: furioncycle <ttecho2021@gmail.com>
> feat: ignore pre-prompt repl warnings

- flake.nix
Co-authored-by: ruben <ruben.beck@pm.me>
Co-authored-by: kurogeek <panupong.jtp@gmail.com>
Co-authored-by: furioncycle <ttecho2021@gmail.com>
> build: integration test in sandbox
